language: go
sudo: false

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.12.x
    env: GO111MODULE=on

install:
  - go get -t -v -d
  - go get github.com/campoy/embedmd

script:
  - embedmd -d *.md

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/acc2c57482e94b44f557
    on_success: change
    on_failure: always
    on_start: false
